<a href="https://colab.research.google.com/github/estebanr2/EstebanRuiz/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
store_one = np.array([2,5,8,3,4,10,15,5])
store_two = np.array([3,17,18,9,2,14,10])
store_three = np.array([7,5,4,3,2,7,7])

# print(np.mean(store_one))
# print(np.mean(store_two))
# print(np.mean(store_three))

coin_toss = np.array([[1,0,0],
                     [0,0,1],
                     [1,0,1]])

print(np.mean(coin_toss))
print(np.mean(coin_toss, axis=0))
print(np.mean(coin_toss, axis=1))

0.4444444444444444
[0.66666667 0.         0.66666667]
[0.33333333 0.33333333 0.66666667]


In [8]:
allergy_trials = np.array([[6,1,3,8,2],
                           [2,6,3,9,8],
                           [5,2,6,9,9]])

print(np.mean(allergy_trials))
print(np.mean(allergy_trials, axis = 1))
print(np.mean(allergy_trials, axis = 0))

5.266666666666667
[4.  5.6 6.2]
[4.33333333 3.         4.         8.66666667 6.33333333]


In [ ]:
import numpy as np
